### ISSUE TITLE
Ajout de filtre 

### ISSUE THREAD

**Issue by dermscan** [jcfrog/easy-trombi#1]
Bonjour,

Serait-ce possible d'ajouter des boutons qui filtre en fonction de champs. 
Exemple dans mon cas par site d'attachement.
Champs:
---
Prénom
Nom
Fonction
Adresse email
Téléphone
Site
---
j'ai vu sur certains site des fonction sous php avec `<div class="colfilterDiv value show">,` c'est peut être une piste?

**Comment by jcfrog** [comment]
un champ de recherche a été ajouté qui permet de filtrer sur le champs indiqués "mandatory" dans le fichier config.php (il faut ajouter dans l'enregistrement `"mandatory" => true`)
